
package UsuariosSocialPOST;

import Clases.AdministradorFunciones;
import Clases.CargarArchivos;
import Clases.Negocio;
import GUIS.IniciarSesion;
import GUIS.Principal;
import static GUIS.Principal.Contador;
import static GUIS.Principal.Contador2;
import GUIS.Registrarse;
import Plegables.AñadirAdministrador;
import static UsuariosSocialPOST.Usuario.AñoUE;
import static UsuariosSocialPOST.Usuario.CorreoElectronicoUE;
import static UsuariosSocialPOST.Usuario.DiaUE;
import static UsuariosSocialPOST.Usuario.ExtencionUE;
import static UsuariosSocialPOST.Usuario.MesUE;
import static UsuariosSocialPOST.Usuario.TipoCorreoUE;
import java.awt.Image;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.imageio.spi.RegisterableService;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;


public class Administrador extends javax.swing.JFrame {
    
    private IniciarSesion iniciar;
    
    private TableRowSorter trsFiltro;
    
    int move;
    
    AdministradorFunciones AF = new AdministradorFunciones(this);

    AñadirAdministrador Añadir;

    public Administrador() {


    }
    
    public IniciarSesion getIniciar(){
        return iniciar;
    }
    
    public Administrador(IniciarSesion iniciar) {
        
        super("Registrarse");
        setResizable(false);
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/SocialPostIcono.png")).getImage());
        initComponents();
        this.iniciar=iniciar;
        setLocation(260, 10);
        
        ImageIcon ImagenBackground = new ImageIcon("src/Imagenes/FondoSocialPOST-Principal.jpg");
        Icon IconoBackground = new ImageIcon(ImagenBackground.getImage().getScaledInstance(PortadaAdministrador.getWidth(), PortadaAdministrador.getHeight(), Image.SCALE_DEFAULT));
        PortadaAdministrador.setIcon(IconoBackground);
        
//        Buscador.setVisible(false);
//        Buscar.setVisible(false);
//        Titulo4.setVisible(false);
        
        llenarTabla();
        CerrarVentana();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PestañaDeAdmin = new javax.swing.JTabbedPane();
        PanelDeControl = new javax.swing.JPanel();
        TipoDeBusqueda = new javax.swing.JComboBox<>();
        ScrollDeInfoUsuarios = new javax.swing.JScrollPane();
        InformacionDeUsuarios = new javax.swing.JTable();
        Separador1 = new javax.swing.JSeparator();
        EliminarUsuario = new javax.swing.JButton();
        EditarUsuario = new javax.swing.JButton();
        ApellidoAdministrador = new javax.swing.JLabel();
        NombreAdministrador = new javax.swing.JLabel();
        SloganAdministrador = new javax.swing.JTextField();
        FotoAdministrador = new javax.swing.JLabel();
        PortadaAdministrador = new javax.swing.JLabel();
        AdministradorBanner = new javax.swing.JLabel();
        Imprimir = new javax.swing.JButton();
        FotoPerfilDeU = new javax.swing.JLabel();
        portadaUsuario = new javax.swing.JLabel();
        Titulo1 = new javax.swing.JLabel();
        Titulo2 = new javax.swing.JLabel();
        Titulo4 = new javax.swing.JLabel();
        Titulo3 = new javax.swing.JLabel();
        Buscador = new javax.swing.JTextField();
        Buscar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        MenuBarAdmin = new javax.swing.JMenuBar();
        UsuarioMenuAdministrador = new javax.swing.JMenu();
        CerrarSesion = new javax.swing.JMenuItem();
        CerrarPrograma = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        PestañaDeAdmin.setBackground(new java.awt.Color(51, 153, 255));
        PestañaDeAdmin.setForeground(new java.awt.Color(255, 255, 255));
        PestañaDeAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        PanelDeControl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PanelDeControl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelDeControlMouseEntered(evt);
            }
        });
        PanelDeControl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TipoDeBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre", "Apellido", "Genero", "Fecha", "Correo", "Contraseña" }));
        TipoDeBusqueda.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TipoDeBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoDeBusquedaActionPerformed(evt);
            }
        });
        PanelDeControl.add(TipoDeBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 590, 140, 20));

        InformacionDeUsuarios.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        InformacionDeUsuarios.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        InformacionDeUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        InformacionDeUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        InformacionDeUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InformacionDeUsuariosMouseClicked(evt);
            }
        });
        ScrollDeInfoUsuarios.setViewportView(InformacionDeUsuarios);

        PanelDeControl.add(ScrollDeInfoUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 480, 260));

        Separador1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        PanelDeControl.add(Separador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 20, 380));

        EliminarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/trash_recycle.png"))); // NOI18N
        EliminarUsuario.setText("Eliminar");
        EliminarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarUsuarioActionPerformed(evt);
            }
        });
        PanelDeControl.add(EliminarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 570, 100, -1));

        EditarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/edit_add.png"))); // NOI18N
        EditarUsuario.setText("Editar");
        EditarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EditarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarUsuarioActionPerformed(evt);
            }
        });
        PanelDeControl.add(EditarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 570, 100, -1));

        ApellidoAdministrador.setBackground(new java.awt.Color(102, 102, 102));
        ApellidoAdministrador.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        ApellidoAdministrador.setForeground(new java.awt.Color(255, 255, 255));
        ApellidoAdministrador.setText(" Administradores");
        ApellidoAdministrador.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ApellidoAdministrador.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ApellidoAdministrador.setOpaque(true);
        PanelDeControl.add(ApellidoAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 150, 20));

        NombreAdministrador.setBackground(new java.awt.Color(0, 0, 0));
        NombreAdministrador.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        NombreAdministrador.setForeground(new java.awt.Color(255, 255, 255));
        NombreAdministrador.setText(" Julian & Lina");
        NombreAdministrador.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        NombreAdministrador.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        NombreAdministrador.setOpaque(true);
        PanelDeControl.add(NombreAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 180, 20));

        SloganAdministrador.setEditable(false);
        SloganAdministrador.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        SloganAdministrador.setText("Administradores del Software");
        SloganAdministrador.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PanelDeControl.add(SloganAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 470, -1));

        FotoAdministrador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FotoAdministrador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/admin-BigIcon.png"))); // NOI18N
        FotoAdministrador.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        FotoAdministrador.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PanelDeControl.add(FotoAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 120, 110));

        PortadaAdministrador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PortadaAdministrador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoSocialPOST-Principal.jpg"))); // NOI18N
        PortadaAdministrador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        PortadaAdministrador.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PanelDeControl.add(PortadaAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 750, 150));

        AdministradorBanner.setBackground(new java.awt.Color(255, 0, 0));
        AdministradorBanner.setFont(new java.awt.Font("Tw Cen MT", 1, 48)); // NOI18N
        AdministradorBanner.setForeground(new java.awt.Color(255, 255, 255));
        AdministradorBanner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AdministradorBanner.setText("Administrador");
        AdministradorBanner.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 0, 0), new java.awt.Color(255, 51, 51), new java.awt.Color(255, 0, 0), new java.awt.Color(153, 0, 0)));
        AdministradorBanner.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        AdministradorBanner.setOpaque(true);
        PanelDeControl.add(AdministradorBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 70));

        Imprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/open_folder.png"))); // NOI18N
        Imprimir.setText("Imprimir");
        Imprimir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImprimirActionPerformed(evt);
            }
        });
        PanelDeControl.add(Imprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 570, 110, -1));

        FotoPerfilDeU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FotoPerfilDeU.setText("Foto ");
        FotoPerfilDeU.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        FotoPerfilDeU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FotoPerfilDeUMouseEntered(evt);
            }
        });
        PanelDeControl.add(FotoPerfilDeU, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 110, 100));

        portadaUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        portadaUsuario.setText("Portada");
        portadaUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        portadaUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                portadaUsuarioMouseEntered(evt);
            }
        });
        PanelDeControl.add(portadaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 190, 70));

        Titulo1.setFont(new java.awt.Font("Tw Cen MT", 1, 22)); // NOI18N
        Titulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo1.setText("Tabla de Usuarios Registrados en SocialPOST");
        Titulo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Titulo1MouseEntered(evt);
            }
        });
        PanelDeControl.add(Titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 440, 30));

        Titulo2.setFont(new java.awt.Font("Tw Cen MT", 1, 22)); // NOI18N
        Titulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo2.setText("Foto de Portada");
        Titulo2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Titulo2MouseEntered(evt);
            }
        });
        PanelDeControl.add(Titulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 150, 30));

        Titulo4.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        Titulo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo4.setText("Buscar Usuario");
        Titulo4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Titulo4MouseEntered(evt);
            }
        });
        PanelDeControl.add(Titulo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 120, 20));

        Titulo3.setFont(new java.awt.Font("Tw Cen MT", 1, 22)); // NOI18N
        Titulo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo3.setText("Foto de Perfil");
        Titulo3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Titulo3MouseEntered(evt);
            }
        });
        PanelDeControl.add(Titulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 150, 30));

        Buscador.setText("Buscar...");
        Buscador.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BuscadorFocusGained(evt);
            }
        });
        Buscador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuscadorMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BuscadorMouseExited(evt);
            }
        });
        Buscador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BuscadorKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BuscadorKeyTyped(evt);
            }
        });
        PanelDeControl.add(Buscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 140, 30));

        Buscar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/search2.png"))); // NOI18N
        Buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });
        PanelDeControl.add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 550, 50, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/user_male_add.png"))); // NOI18N
        jButton1.setText("Añadir");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        PanelDeControl.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 570, 110, -1));
        PanelDeControl.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 750, 20));

        PestañaDeAdmin.addTab("Panel de Control", PanelDeControl);

        MenuBarAdmin.setBackground(new java.awt.Color(0, 0, 0));
        MenuBarAdmin.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        UsuarioMenuAdministrador.setForeground(new java.awt.Color(255, 255, 255));
        UsuarioMenuAdministrador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/admin.png"))); // NOI18N
        UsuarioMenuAdministrador.setText("Administrador");
        UsuarioMenuAdministrador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        CerrarSesion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        CerrarSesion.setBackground(new java.awt.Color(102, 102, 102));
        CerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        CerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/exit.png"))); // NOI18N
        CerrarSesion.setText("Cerrar Sesion");
        CerrarSesion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        CerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CerrarSesion.setOpaque(true);
        CerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarSesionActionPerformed(evt);
            }
        });
        UsuarioMenuAdministrador.add(CerrarSesion);

        CerrarPrograma.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_END, 0));
        CerrarPrograma.setBackground(new java.awt.Color(102, 102, 102));
        CerrarPrograma.setForeground(new java.awt.Color(255, 255, 255));
        CerrarPrograma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/CerrarVentana.png"))); // NOI18N
        CerrarPrograma.setText("Cerrar Programa");
        CerrarPrograma.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        CerrarPrograma.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CerrarPrograma.setOpaque(true);
        CerrarPrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarProgramaActionPerformed(evt);
            }
        });
        UsuarioMenuAdministrador.add(CerrarPrograma);

        MenuBarAdmin.add(UsuarioMenuAdministrador);

        setJMenuBar(MenuBarAdmin);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PestañaDeAdmin)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PestañaDeAdmin)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public Administrador(IniciarSesion iniciar, JLabel AdministradorBanner, JLabel ApellidoAdministrador, JTextField Buscador, JButton Buscar, JMenuItem CerrarPrograma, JMenuItem CerrarSesion, JLabel EditBtn, JLabel EditBtn2, JButton EditarUsuario, JButton EliminarUsuario, JLabel FotoAdministrador, JLabel FotoPerfilDeU, JButton Imprimir, JTable InformacionDeUsuarios, JMenuBar MenuBarAdmin, JLabel NombreAdministrador, JPanel PanelDeControl, JTabbedPane PestañaDeAdmin, JLabel PortadaAdministrador, JScrollPane ScrollDeInfoUsuarios, JSeparator Separador1, JTextField SloganAdministrador, JLabel Titulo1, JLabel Titulo2, JLabel Titulo3, JLabel Titulo4, JMenu UsuarioMenuAdministrador, JButton jButton1, JLabel jLabel1, JLabel portadaUsuario) {
        this.iniciar = iniciar;
        this.AdministradorBanner = AdministradorBanner;
        this.ApellidoAdministrador = ApellidoAdministrador;
        this.Buscador = Buscador;
        this.Buscar = Buscar;
        this.CerrarPrograma = CerrarPrograma;
        this.CerrarSesion = CerrarSesion;
        this.EditarUsuario = EditarUsuario;
        this.EliminarUsuario = EliminarUsuario;
        this.FotoAdministrador = FotoAdministrador;
        this.FotoPerfilDeU = FotoPerfilDeU;
        this.Imprimir = Imprimir;
        this.InformacionDeUsuarios = InformacionDeUsuarios;
        this.MenuBarAdmin = MenuBarAdmin;
        this.NombreAdministrador = NombreAdministrador;
        this.PanelDeControl = PanelDeControl;
        this.PestañaDeAdmin = PestañaDeAdmin;
        this.PortadaAdministrador = PortadaAdministrador;
        this.ScrollDeInfoUsuarios = ScrollDeInfoUsuarios;
        this.Separador1 = Separador1;
        this.SloganAdministrador = SloganAdministrador;
        this.Titulo1 = Titulo1;
        this.Titulo2 = Titulo2;
        this.Titulo3 = Titulo3;
        this.Titulo4 = Titulo4;
        this.UsuarioMenuAdministrador = UsuarioMenuAdministrador;
        this.jButton1 = jButton1;
        this.jLabel1 = jLabel1;
        this.portadaUsuario = portadaUsuario;
    }

    public AdministradorFunciones getAF() {
        return AF;
    }

    public void setAF(AdministradorFunciones AF) {
        this.AF = AF;
    }

    public JLabel getAdministradorBanner() {
        return AdministradorBanner;
    }

    public void setAdministradorBanner(JLabel AdministradorBanner) {
        this.AdministradorBanner = AdministradorBanner;
    }

    public JLabel getApellidoAdministrador() {
        return ApellidoAdministrador;
    }

    public void setApellidoAdministrador(JLabel ApellidoAdministrador) {
        this.ApellidoAdministrador = ApellidoAdministrador;
    }

    public JTextField getBuscador() {
        return Buscador;
    }

    public void setBuscador(JTextField Buscador) {
        this.Buscador = Buscador;
    }

    public JButton getBuscar() {
        return Buscar;
    }

    public void setBuscar(JButton Buscar) {
        this.Buscar = Buscar;
    }

    public JMenuItem getCerrarPrograma() {
        return CerrarPrograma;
    }

    public void setCerrarPrograma(JMenuItem CerrarPrograma) {
        this.CerrarPrograma = CerrarPrograma;
    }

    public JMenuItem getCerrarSesion() {
        return CerrarSesion;
    }

    public void setCerrarSesion(JMenuItem CerrarSesion) {
        this.CerrarSesion = CerrarSesion;
    }

    public JButton getEditarUsuario() {
        return EditarUsuario;
    }

    public void setEditarUsuario(JButton EditarUsuario) {
        this.EditarUsuario = EditarUsuario;
    }

    public JButton getEliminarUsuario() {
        return EliminarUsuario;
    }

    public void setEliminarUsuario(JButton EliminarUsuario) {
        this.EliminarUsuario = EliminarUsuario;
    }

    public JLabel getFotoAdministrador() {
        return FotoAdministrador;
    }

    public void setFotoAdministrador(JLabel FotoAdministrador) {
        this.FotoAdministrador = FotoAdministrador;
    }

    public JLabel getFotoPerfilDeU() {
        return FotoPerfilDeU;
    }

    public void setFotoPerfilDeU(JLabel FotoPerfilDeU) {
        this.FotoPerfilDeU = FotoPerfilDeU;
    }

    public JButton getImprimir() {
        return Imprimir;
    }

    public void setImprimir(JButton Imprimir) {
        this.Imprimir = Imprimir;
    }

    public JTable getInformacionDeUsuarios() {
        return InformacionDeUsuarios;
    }

    public void setInformacionDeUsuarios(JTable InformacionDeUsuarios) {
        this.InformacionDeUsuarios = InformacionDeUsuarios;
    }

    public JMenuBar getMenuBarAdmin() {
        return MenuBarAdmin;
    }

    public void setMenuBarAdmin(JMenuBar MenuBarAdmin) {
        this.MenuBarAdmin = MenuBarAdmin;
    }

    public JLabel getNombreAdministrador() {
        return NombreAdministrador;
    }

    public void setNombreAdministrador(JLabel NombreAdministrador) {
        this.NombreAdministrador = NombreAdministrador;
    }

    public JPanel getPanelDeControl() {
        return PanelDeControl;
    }

    public void setPanelDeControl(JPanel PanelDeControl) {
        this.PanelDeControl = PanelDeControl;
    }

    public JTabbedPane getPestañaDeAdmin() {
        return PestañaDeAdmin;
    }

    public void setPestañaDeAdmin(JTabbedPane PestañaDeAdmin) {
        this.PestañaDeAdmin = PestañaDeAdmin;
    }

    public JLabel getPortadaAdministrador() {
        return PortadaAdministrador;
    }

    public void setPortadaAdministrador(JLabel PortadaAdministrador) {
        this.PortadaAdministrador = PortadaAdministrador;
    }

    public JScrollPane getScrollDeInfoUsuarios() {
        return ScrollDeInfoUsuarios;
    }

    public void setScrollDeInfoUsuarios(JScrollPane ScrollDeInfoUsuarios) {
        this.ScrollDeInfoUsuarios = ScrollDeInfoUsuarios;
    }

    public JSeparator getSeparador1() {
        return Separador1;
    }

    public void setSeparador1(JSeparator Separador1) {
        this.Separador1 = Separador1;
    }

    public JTextField getSloganAdministrador() {
        return SloganAdministrador;
    }

    public void setSloganAdministrador(JTextField SloganAdministrador) {
        this.SloganAdministrador = SloganAdministrador;
    }

    public JLabel getTitulo1() {
        return Titulo1;
    }

    public void setTitulo1(JLabel Titulo1) {
        this.Titulo1 = Titulo1;
    }

    public JLabel getTitulo2() {
        return Titulo2;
    }

    public void setTitulo2(JLabel Titulo2) {
        this.Titulo2 = Titulo2;
    }

    public JLabel getTitulo3() {
        return Titulo3;
    }

    public void setTitulo3(JLabel Titulo3) {
        this.Titulo3 = Titulo3;
    }

    public JLabel getTitulo4() {
        return Titulo4;
    }

    public void setTitulo4(JLabel Titulo4) {
        this.Titulo4 = Titulo4;
    }

    public JMenu getUsuarioMenuAdministrador() {
        return UsuarioMenuAdministrador;
    }

    public void setUsuarioMenuAdministrador(JMenu UsuarioMenuAdministrador) {
        this.UsuarioMenuAdministrador = UsuarioMenuAdministrador;
    }

    public JButton getjButton1() {
        return jButton1;
    }

    public void setjButton1(JButton jButton1) {
        this.jButton1 = jButton1;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getPortadaUsuario() {
        return portadaUsuario;
    }

    public void setPortadaUsuario(JLabel portadaUsuario) {
        this.portadaUsuario = portadaUsuario;
    }
    


    private void CerrarProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarProgramaActionPerformed
        
        JOptionPane.showMessageDialog(null, "Gracias por tu visita Administrador", "ADIOS", JOptionPane.INFORMATION_MESSAGE);
        
        System.exit(0);
        
    }//GEN-LAST:event_CerrarProgramaActionPerformed

    private void CerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarSesionActionPerformed
        
        dispose();

        iniciar.getPrincipal().setVisible(true);
        
        Contador = Contador - Contador;
        Contador2 = Contador2 - Contador2;
        
        JOptionPane.showMessageDialog(null, "Hasta pronto Administrador", "ADIOS, VUELVE PRONTO", JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_CerrarSesionActionPerformed

    private void ImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImprimirActionPerformed

        llenarTabla();

    }//GEN-LAST:event_ImprimirActionPerformed

    private void EditarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarUsuarioActionPerformed

        int personaSeleccionada=InformacionDeUsuarios.getSelectedRow();
        int datoSeleccionado= InformacionDeUsuarios.getSelectedColumn();
        String correo=InformacionDeUsuarios.getValueAt(personaSeleccionada, 4).toString();
        String nco =InformacionDeUsuarios.getModel().getColumnName(datoSeleccionado);
        int respuesta= JOptionPane.showConfirmDialog(null, "Estas seguro que deseas modificar "+nco);

        if (respuesta==0) {
            String dato= JOptionPane.showInputDialog(null, "Ingrese "+nco, "Ingrese "+nco);
            if (dato!=null && !dato.trim().isEmpty()) {

                try {
                    this.iniciar.getPrincipal().getNegocio().editarDatoAdmin(nco.toLowerCase(),dato , correo);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }
            }
        }else{

        }

        llenarTabla();

    }//GEN-LAST:event_EditarUsuarioActionPerformed

    private void EliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarUsuarioActionPerformed

        int Si = JOptionPane.showConfirmDialog(null, "¿Segur@ que deseas eliminar este usuario?");
        
        if(JOptionPane.YES_OPTION == Si){
        
            this.iniciar.getPrincipal().getNegocio().eliminarUsuario(this.sacarCorreoTabla());
            llenarTabla();
            FotoPerfilDeU.setIcon(null);
            portadaUsuario.setIcon(null);
        
        }
        
    }//GEN-LAST:event_EliminarUsuarioActionPerformed

    private void InformacionDeUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InformacionDeUsuariosMouseClicked
        Seleccionar();
    }//GEN-LAST:event_InformacionDeUsuariosMouseClicked

    private void BuscadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscadorMouseClicked
        
        AF.MouseClickBuscardor();
        
    }//GEN-LAST:event_BuscadorMouseClicked

    private void BuscadorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BuscadorFocusGained
        
        AF.MouseClickBuscardor();
        
    }//GEN-LAST:event_BuscadorFocusGained

    private void BuscadorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscadorMouseExited
        
        AF.MouseClickFueraBuscador();
        
    }//GEN-LAST:event_BuscadorMouseExited

    private void BuscadorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BuscadorKeyPressed
        
        //AF.TecladoBuscador(evt);

        
        char Entrar = evt.getKeyChar();
        char Cambiar = evt.getKeyChar();

        if (evt.getKeyCode() == evt.VK_ENTER) {

            Buscar.doClick();
        }

        if (evt.getKeyCode() == evt.VK_DOWN) {

            move++;

            //System.out.println("sumar move: "+move);
            if (move > 5) {

                move = 5;

            } else {

                TipoDeBusqueda.setSelectedIndex(move);

            }
           
        }

        if (evt.getKeyCode() == evt.VK_UP) {

            move--;
            //System.out.println("restar move: "+move);

            if (move < 0) {

                move = 0;

            } else {

                TipoDeBusqueda.setSelectedIndex(move);

            }

        }
        
    }//GEN-LAST:event_BuscadorKeyPressed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        
        
        
    }//GEN-LAST:event_BuscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        AñadirAdministrador AA = new AñadirAdministrador(this, rootPaneCheckingEnabled, this);
        AA.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void PanelDeControlMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelDeControlMouseEntered
        
        AF.MouseClickDentroBuscador();
        
    }//GEN-LAST:event_PanelDeControlMouseEntered

    private void FotoPerfilDeUMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FotoPerfilDeUMouseEntered
        
        AF.MouseClickDentroBuscador();
        
    }//GEN-LAST:event_FotoPerfilDeUMouseEntered

    private void portadaUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_portadaUsuarioMouseEntered
        
        AF.MouseClickDentroBuscador();
        
    }//GEN-LAST:event_portadaUsuarioMouseEntered

    private void Titulo3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Titulo3MouseEntered
        
        AF.MouseClickDentroBuscador();
        
    }//GEN-LAST:event_Titulo3MouseEntered

    private void Titulo2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Titulo2MouseEntered
        
        AF.MouseClickDentroBuscador();
        
    }//GEN-LAST:event_Titulo2MouseEntered

    private void Titulo4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Titulo4MouseEntered
        
        AF.MouseClickDentroBuscador();
        
    }//GEN-LAST:event_Titulo4MouseEntered

    private void Titulo1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Titulo1MouseEntered
        
        AF.MouseClickDentroBuscador();
        
    }//GEN-LAST:event_Titulo1MouseEntered

    private void TipoDeBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoDeBusquedaActionPerformed
        
        if (TipoDeBusqueda.getSelectedItem().toString() == "Nombre") {

            repaint();
            filtro1();
        }
        if (TipoDeBusqueda.getSelectedItem().toString() == "Apellido") {

            repaint();
            filtro1();
        }
        if (TipoDeBusqueda.getSelectedItem() == "Genero") {

            repaint();
            filtro1();
        }
        if (TipoDeBusqueda.getSelectedItem() == "Fecha") {

            repaint();
            filtro1();
        }
        if (TipoDeBusqueda.getSelectedItem() == "Correo") {

            repaint();
            filtro1();
        }
        if (TipoDeBusqueda.getSelectedItem() == "Contraseña") {

            repaint();
            filtro1();

        }
        
    }//GEN-LAST:event_TipoDeBusquedaActionPerformed

    private void BuscadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BuscadorKeyTyped
        Buscador.addKeyListener(new KeyAdapter() {
            public void keyReleased(final KeyEvent e) {

                String cadena = (Buscador.getText());
                Buscador.setText(cadena);
                repaint();
                filtro1();
            }

        });

        trsFiltro = new TableRowSorter(InformacionDeUsuarios.getModel());
        InformacionDeUsuarios.setRowSorter(trsFiltro);
    }//GEN-LAST:event_BuscadorKeyTyped

    private void filtro1() {

        int columnaBuscar = 0;

        if (TipoDeBusqueda.getSelectedItem().toString() == "Nombre") {

            columnaBuscar = 0;
        }
        if (TipoDeBusqueda.getSelectedItem().toString() == "Apellido") {

            columnaBuscar = 1;
        }
        if (TipoDeBusqueda.getSelectedItem() == "Genero") {

            columnaBuscar = 2;
        }
        if (TipoDeBusqueda.getSelectedItem() == "Fecha") {

            columnaBuscar = 3;
        }
        if (TipoDeBusqueda.getSelectedItem() == "Correo") {

            columnaBuscar = 4;
        }
        if (TipoDeBusqueda.getSelectedItem() == "Contraseña") {

            columnaBuscar = 5;

        }
        
        trsFiltro.setRowFilter(RowFilter.regexFilter(Buscador.getText(), columnaBuscar));

    }
    
    private String sacarCorreoTabla(){
        return InformacionDeUsuarios.getValueAt(InformacionDeUsuarios.getSelectedRow(), 4).toString();
    }
    
 
    private void Seleccionar(){
        String[][] informacion= this.iniciar.getPrincipal().getNegocio().ImprimirUsuario();
          
        int personaSeleccionada=InformacionDeUsuarios.getSelectedRow();
        CargarArchivos aux=new CargarArchivos(null);
        
         aux.CargarFoto(informacion[personaSeleccionada][6]==null ?"src/Iconos/TradicionalUser-BigIcon.png":informacion[personaSeleccionada][6], FotoPerfilDeU);
        
      
         aux.CargarFoto(informacion[personaSeleccionada][7]==null ?"src/Imagenes/FondoSocialPOST-Principal.jpg":informacion[personaSeleccionada][7],portadaUsuario);
        
    }
 
    private void llenarTabla(){
        String[][] informacion= this.iniciar.getPrincipal().getNegocio().ImprimirUsuario();
        String []cabeceras = {"Nombre","Apellido","Genero","Fecha","Correo","Contraseña"};
        InformacionDeUsuarios.setModel(new DefaultTableModel(informacion,cabeceras));
  
    }

    public void CerrarVentana(){

        try{
    
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            addWindowListener(new WindowAdapter(){
            public void windowClosing(WindowEvent e){
                confirmarSalida();
                
            }
        });
        
        this.setVisible(true);
        }catch(Exception e){
            e.printStackTrace();
        }

    }

    public void confirmarSalida(){

        JOptionPane.showMessageDialog(null, "Estas intentando cerrar la aplicacion sin cerrar sesión primero", "ADVENTENCIA", JOptionPane.WARNING_MESSAGE);
        int valor = JOptionPane.showConfirmDialog(this, "¿Deseas cerrar sesión y la aplicacion al mismo tiempo?", "ADVERTENCIA", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if(valor==JOptionPane.YES_OPTION){
        
            JOptionPane.showMessageDialog(null, "Gracias por su visita, vuelve pronto", "HASTA LUEGO", JOptionPane.INFORMATION_MESSAGE);
            //this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            System.exit(0);
        
        }else if(valor == JOptionPane.YES_NO_CANCEL_OPTION){
            
        }

    
    }
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdministradorBanner;
    private javax.swing.JLabel ApellidoAdministrador;
    private javax.swing.JTextField Buscador;
    private javax.swing.JButton Buscar;
    private javax.swing.JMenuItem CerrarPrograma;
    private javax.swing.JMenuItem CerrarSesion;
    private javax.swing.JButton EditarUsuario;
    private javax.swing.JButton EliminarUsuario;
    private javax.swing.JLabel FotoAdministrador;
    private javax.swing.JLabel FotoPerfilDeU;
    private javax.swing.JButton Imprimir;
    private javax.swing.JTable InformacionDeUsuarios;
    private javax.swing.JMenuBar MenuBarAdmin;
    private javax.swing.JLabel NombreAdministrador;
    private javax.swing.JPanel PanelDeControl;
    private javax.swing.JTabbedPane PestañaDeAdmin;
    private javax.swing.JLabel PortadaAdministrador;
    private javax.swing.JScrollPane ScrollDeInfoUsuarios;
    private javax.swing.JSeparator Separador1;
    private javax.swing.JTextField SloganAdministrador;
    private javax.swing.JComboBox<String> TipoDeBusqueda;
    private javax.swing.JLabel Titulo1;
    private javax.swing.JLabel Titulo2;
    private javax.swing.JLabel Titulo3;
    private javax.swing.JLabel Titulo4;
    private javax.swing.JMenu UsuarioMenuAdministrador;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel portadaUsuario;
    // End of variables declaration//GEN-END:variables
}
