
package Plegables;

import Clases.RegistrarseFunciones;
import GUIS.Registrarse;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;


public class AgregarAño1 extends javax.swing.JDialog {

    RegistrarseFunciones Agregar;
    
    public AgregarAño1(java.awt.Frame parent, boolean modal, RegistrarseFunciones Agregar) {
        super(parent, modal);
        initComponents();
        setLocation(670, 310);
        this.Agregar = Agregar;
        
        SpinnerNumberModel AS = new SpinnerNumberModel();
        AS.setMaximum(2018);
        AS.setMinimum(1000);
        AS.setValue(1000);
        AñoSpinner.setModel(AS);
    }

    public AgregarAño1(RegistrarseFunciones RF, Registrarse RE, JSpinner AñoSpinner, JButton IngresarAño, JPanel PanelAñoPlegable, JButton SeleccionarAño, JLabel Texto) {
        this.AñoSpinner = AñoSpinner;
        this.IngresarAño = IngresarAño;
        this.PanelAñoPlegable = PanelAñoPlegable;
        this.SeleccionarAño = SeleccionarAño;
        this.Texto = Texto;
    }

    public JSpinner getAñoSpinner() {
        return AñoSpinner;
    }

    public void setAñoSpinner(JSpinner AñoSpinner) {
        this.AñoSpinner = AñoSpinner;
    }

    public JButton getIngresarAño() {
        return IngresarAño;
    }

    public void setIngresarAño(JButton IngresarAño) {
        this.IngresarAño = IngresarAño;
    }

    public JPanel getPanelAñoPlegable() {
        return PanelAñoPlegable;
    }

    public void setPanelAñoPlegable(JPanel PanelAñoPlegable) {
        this.PanelAñoPlegable = PanelAñoPlegable;
    }

    public JButton getSeleccionarAño() {
        return SeleccionarAño;
    }

    public void setSeleccionarAño(JButton SeleccionarAño) {
        this.SeleccionarAño = SeleccionarAño;
    }

    public JLabel getTexto() {
        return Texto;
    }

    public void setTexto(JLabel Texto) {
        this.Texto = Texto;
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelAñoPlegable = new javax.swing.JPanel();
        AñoSpinner = new javax.swing.JSpinner();
        IngresarAño = new javax.swing.JButton();
        SeleccionarAño = new javax.swing.JButton();
        Texto = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        PanelAñoPlegable.setBackground(new java.awt.Color(255, 255, 255));
        PanelAñoPlegable.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AñoSpinner.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        AñoSpinner.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AñoSpinnerKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AñoSpinnerKeyTyped(evt);
            }
        });
        PanelAñoPlegable.add(AñoSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 80, 30));

        IngresarAño.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/save.png"))); // NOI18N
        IngresarAño.setText("Guardar");
        IngresarAño.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        IngresarAño.setOpaque(false);
        IngresarAño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarAñoActionPerformed(evt);
            }
        });
        PanelAñoPlegable.add(IngresarAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 110, 30));

        SeleccionarAño.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/CerrarVentana.png"))); // NOI18N
        SeleccionarAño.setText("Cancelar");
        SeleccionarAño.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SeleccionarAño.setOpaque(false);
        SeleccionarAño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionarAñoActionPerformed(evt);
            }
        });
        PanelAñoPlegable.add(SeleccionarAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 110, 30));

        Texto.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        Texto.setText("<html>Ingresa y/o Selecciona tu año.</html>");
        PanelAñoPlegable.add(Texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 120, 50));

        Background.setOpaque(true);
        PanelAñoPlegable.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 250, 120));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelAñoPlegable, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelAñoPlegable, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AñoSpinnerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AñoSpinnerKeyPressed

        Agregar.BloquearPegadoAltYShitf(evt);

    }//GEN-LAST:event_AñoSpinnerKeyPressed

    private void AñoSpinnerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AñoSpinnerKeyTyped

        Agregar.ValidarSolamenteNumeros(evt);

    }//GEN-LAST:event_AñoSpinnerKeyTyped

    private void IngresarAñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarAñoActionPerformed

        Agregar.AñadirAño();

    }//GEN-LAST:event_IngresarAñoActionPerformed

    private void SeleccionarAñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionarAñoActionPerformed

        Agregar.getRegistrarse().getAño().setSelectedItem("2018");
        dispose();

    }//GEN-LAST:event_SeleccionarAñoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner AñoSpinner;
    private javax.swing.JLabel Background;
    private javax.swing.JButton IngresarAño;
    private javax.swing.JPanel PanelAñoPlegable;
    private javax.swing.JButton SeleccionarAño;
    private javax.swing.JLabel Texto;
    // End of variables declaration//GEN-END:variables
}
