
package Plegables;

import javax.swing.JOptionPane;
import static Clases.UsuarioBD.hostDB;
import static Clases.UsuarioBD.puertoDB;
import static Clases.UsuarioBD.userDB;
import static Clases.UsuarioBD.passDB;
import javax.swing.SpinnerNumberModel;

public class ConfigureHost extends javax.swing.JDialog {


    public ConfigureHost(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);
        
        SpinnerNumberModel AS = new SpinnerNumberModel();
        AS.setMaximum(9999);
        AS.setMinimum(1000);
        AS.setValue(3306);
        puertoDB2.setModel(AS);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelAñoPlegable = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        veriPassDB2 = new javax.swing.JCheckBox();
        TextoPass = new javax.swing.JLabel();
        passDB2 = new javax.swing.JTextField();
        TextoUser = new javax.swing.JLabel();
        userDB2 = new javax.swing.JTextField();
        TextoPuerto = new javax.swing.JLabel();
        puertoDB2 = new javax.swing.JSpinner();
        TextoHost = new javax.swing.JLabel();
        hostDB2 = new javax.swing.JTextField();
        guardar = new javax.swing.JButton();
        porDefecto = new javax.swing.JButton();
        Texto = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        PanelAñoPlegable.setBackground(new java.awt.Color(255, 255, 255));
        PanelAñoPlegable.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/CerrarVentana.png"))); // NOI18N
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        PanelAñoPlegable.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 30, 30));

        veriPassDB2.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        veriPassDB2.setText("Sin contraseña");
        veriPassDB2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        veriPassDB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veriPassDB2ActionPerformed(evt);
            }
        });
        PanelAñoPlegable.add(veriPassDB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 110, -1));

        TextoPass.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        TextoPass.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        TextoPass.setText("<html>Contraseña:</html>");
        PanelAñoPlegable.add(TextoPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 90, 20));
        PanelAñoPlegable.add(passDB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 110, 20));

        TextoUser.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        TextoUser.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        TextoUser.setText("<html>Usuario:</html>");
        PanelAñoPlegable.add(TextoUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 90, 20));
        PanelAñoPlegable.add(userDB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 110, 20));

        TextoPuerto.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        TextoPuerto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        TextoPuerto.setText("<html>Puerto:</html>");
        PanelAñoPlegable.add(TextoPuerto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 90, 20));

        puertoDB2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        puertoDB2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                puertoDB2KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                puertoDB2KeyTyped(evt);
            }
        });
        PanelAñoPlegable.add(puertoDB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 110, 20));

        TextoHost.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        TextoHost.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        TextoHost.setText("<html>Host:</html>");
        PanelAñoPlegable.add(TextoHost, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 90, 20));
        PanelAñoPlegable.add(hostDB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 110, 20));

        guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/save.png"))); // NOI18N
        guardar.setText("Guardar");
        guardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        guardar.setOpaque(false);
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        PanelAñoPlegable.add(guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 120, 30));

        porDefecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/default_Archives_Small.png"))); // NOI18N
        porDefecto.setText("Por defecto");
        porDefecto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        porDefecto.setOpaque(false);
        porDefecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                porDefectoActionPerformed(evt);
            }
        });
        PanelAñoPlegable.add(porDefecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 120, 30));

        Texto.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        Texto.setText("<html><center>Configura los parametros del hosting</center></html>");
        PanelAñoPlegable.add(Texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 220, 30));

        Background.setOpaque(true);
        PanelAñoPlegable.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, 310));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelAñoPlegable, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelAñoPlegable, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed

        if (veriPassDB2.isSelected()) {

            if (hostDB2.getText().equals("") && userDB2.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Sus campos estan vacios", "Alerta", JOptionPane.INFORMATION_MESSAGE);
            } else if (hostDB2.getText().isEmpty() || userDB2.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Alguno de sus campos esta vacio", "Alerta", JOptionPane.INFORMATION_MESSAGE);
            } else {

                hostDB = hostDB2.getText();
                puertoDB = puertoDB2.getValue().toString();
                userDB = userDB2.getText();
                passDB = "";

                System.out.println("\nSe establecio una nueva conexion en:\nHost: " + hostDB + "\nPuerto: " + puertoDB + "\nUsuario: " + userDB + "\nContraseña: " + passDB);

                JOptionPane.showMessageDialog(null, "Se establecio una nueva conexion en:\n"
                        + "\nHost: " + hostDB + "\nPuerto: " + puertoDB + "\nUsuario: " + userDB + "\nContraseña: sin contraseña", "Conexion Establecida", JOptionPane.INFORMATION_MESSAGE);

            }

        } else if (!veriPassDB2.isSelected()) {

            if (hostDB2.getText().equals("") && userDB2.getText().equals("") && passDB2.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Sus campos estan vacios", "Alerta", JOptionPane.INFORMATION_MESSAGE);
            } else if (hostDB2.getText().isEmpty() && userDB2.getText().isEmpty() || hostDB2.getText().isEmpty() && passDB2.getText().isEmpty() || userDB2.getText().isEmpty() && passDB2.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Sus campos estan vacios", "Alerta", JOptionPane.INFORMATION_MESSAGE);
            } else if (hostDB2.getText().isEmpty() || userDB2.getText().isEmpty() || passDB2.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Alguno de sus campos esta vacio", "Alerta", JOptionPane.INFORMATION_MESSAGE);
            } else {

                hostDB = hostDB2.getText();
                puertoDB = puertoDB2.getValue().toString();
                userDB = userDB2.getText();
                passDB = passDB2.getText();

                System.out.println("\nSe establecio una nueva conexion en:\nHost: " + hostDB + "\nPuerto: " + puertoDB + "\nUsuario: " + userDB + "\nContraseña: " + passDB);

                JOptionPane.showMessageDialog(null, "Se establecio una nueva conexion en:\n"
                        + "\nHost: " + hostDB + "\nPuerto: " + puertoDB + "\nUsuario: " + userDB + "\nContraseña: " + passDB, "Conexion Establecida", JOptionPane.INFORMATION_MESSAGE);

            }

        }
        
    }//GEN-LAST:event_guardarActionPerformed

    private void porDefectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_porDefectoActionPerformed
        int confirm = JOptionPane.showConfirmDialog(rootPane, "¿Estas seguro que deseas usar los parametros por defecto?","Abvertencia!",JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (confirm == JOptionPane.YES_OPTION) {
            hostDB2.setText("localhost");
            puertoDB2.setValue(3306);
            userDB2.setText("root");
            passDB2.setText("");
            veriPassDB2.setSelected(true);
            passDB2.setEditable(false);
            TextoPass.setText("<html>Sin contraseña</html>");
        }        
    }//GEN-LAST:event_porDefectoActionPerformed

    private void puertoDB2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_puertoDB2KeyPressed

    }//GEN-LAST:event_puertoDB2KeyPressed

    private void puertoDB2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_puertoDB2KeyTyped

    }//GEN-LAST:event_puertoDB2KeyTyped

    private void veriPassDB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veriPassDB2ActionPerformed
        if (veriPassDB2.isSelected()) {
            passDB2.setEditable(false);
            passDB2.setText("");
            TextoPass.setText("<html>Sin contraseña</html>");
        }else if (!veriPassDB2.isSelected()) {
            passDB2.setEditable(true);
            TextoPass.setText("<html>Contraseña:</html>");
        }
 
    }//GEN-LAST:event_veriPassDB2ActionPerformed

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        dispose();
    }//GEN-LAST:event_closeMouseClicked

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfigureHost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfigureHost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfigureHost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfigureHost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ConfigureHost dialog = new ConfigureHost(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JPanel PanelAñoPlegable;
    private javax.swing.JLabel Texto;
    private javax.swing.JLabel TextoHost;
    private javax.swing.JLabel TextoPass;
    private javax.swing.JLabel TextoPuerto;
    private javax.swing.JLabel TextoUser;
    private javax.swing.JLabel close;
    private javax.swing.JButton guardar;
    private javax.swing.JTextField hostDB2;
    private javax.swing.JTextField passDB2;
    private javax.swing.JButton porDefecto;
    private javax.swing.JSpinner puertoDB2;
    private javax.swing.JTextField userDB2;
    private javax.swing.JCheckBox veriPassDB2;
    // End of variables declaration//GEN-END:variables
}
