
package Plegables;

import javax.swing.JOptionPane;
import static Clases.UsuarioBD.sqlDB;
import static Clases.UsuarioBD.driverDB;
import static Clases.UsuarioBD.gestorDB;
import javax.swing.SpinnerNumberModel;

public class ConfigureDB extends javax.swing.JDialog {


    public ConfigureDB(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);
        
        ejemploRuta.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelAñoPlegable = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        TextoUrl1 = new javax.swing.JLabel();
        ejemploRuta = new javax.swing.JTextField();
        TextoGestor = new javax.swing.JLabel();
        gestorBD = new javax.swing.JTextField();
        TextoUrl = new javax.swing.JLabel();
        rutaBD = new javax.swing.JTextField();
        TextoNombre = new javax.swing.JLabel();
        nameBD = new javax.swing.JTextField();
        IngresarAño = new javax.swing.JButton();
        porDefecto = new javax.swing.JButton();
        Texto = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        PanelAñoPlegable.setBackground(new java.awt.Color(255, 255, 255));
        PanelAñoPlegable.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/CerrarVentana.png"))); // NOI18N
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        PanelAñoPlegable.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 30, 30));

        TextoUrl1.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        TextoUrl1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        TextoUrl1.setText("<html>Ejemplo de Ruta:</html>");
        PanelAñoPlegable.add(TextoUrl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 90, -1));

        ejemploRuta.setText("com.mysql.jdbc.Driver");
        PanelAñoPlegable.add(ejemploRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 130, 20));

        TextoGestor.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        TextoGestor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        TextoGestor.setText("<html>Gestor de Base de Datos:</html>");
        PanelAñoPlegable.add(TextoGestor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 90, 40));
        PanelAñoPlegable.add(gestorBD, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 130, 20));

        TextoUrl.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        TextoUrl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        TextoUrl.setText("<html>Ruta del Driver:</html>");
        PanelAñoPlegable.add(TextoUrl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 90, 20));
        PanelAñoPlegable.add(rutaBD, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 130, 20));

        TextoNombre.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        TextoNombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        TextoNombre.setText("<html>Nombre de la Base de Datos:</html>");
        PanelAñoPlegable.add(TextoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 90, 40));
        PanelAñoPlegable.add(nameBD, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 130, 20));

        IngresarAño.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/save.png"))); // NOI18N
        IngresarAño.setText("Guardar");
        IngresarAño.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        IngresarAño.setOpaque(false);
        IngresarAño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarAñoActionPerformed(evt);
            }
        });
        PanelAñoPlegable.add(IngresarAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 120, 30));

        porDefecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/default_Archives_Small.png"))); // NOI18N
        porDefecto.setText("Por defecto");
        porDefecto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        porDefecto.setOpaque(false);
        porDefecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                porDefectoActionPerformed(evt);
            }
        });
        PanelAñoPlegable.add(porDefecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 120, 30));

        Texto.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        Texto.setText("<html><center>Configura la Base de Datos</center></html>");
        PanelAñoPlegable.add(Texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 160, 30));

        Background.setOpaque(true);
        PanelAñoPlegable.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, 330));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelAñoPlegable, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelAñoPlegable, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IngresarAñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarAñoActionPerformed
            if (nameBD.getText().equals("") && gestorBD.getText().equals("") && rutaBD.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Sus campos estan vacios", "Alerta", JOptionPane.INFORMATION_MESSAGE);
            } else if (nameBD.getText().isEmpty() && gestorBD.getText().isEmpty() || nameBD.getText().isEmpty() && rutaBD.getText().isEmpty() || gestorBD.getText().isEmpty() && rutaBD.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Sus campos estan vacios", "Alerta", JOptionPane.INFORMATION_MESSAGE);
            } else if (nameBD.getText().isEmpty() || gestorBD.getText().isEmpty() || rutaBD.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Alguno de sus campos esta vacio", "Alerta", JOptionPane.INFORMATION_MESSAGE);
            } else {

                sqlDB = nameBD.getText();
                gestorDB = gestorBD.getText();
                driverDB = rutaBD.getText();

                System.out.println("\nSe establecio la siguiente base de datos como:\n"
                        + "\nBase de Datos: " + sqlDB +  "\nGestor de Datos: " + gestorDB + "\nRuta del Driver: " + driverDB);

                JOptionPane.showMessageDialog(null, "Se establecio la siguiente base de datos como:\n"
                        + "\nBase de Datos: " + sqlDB + "\nGestor de Datos: " + gestorDB + "\nRuta del Driver: " + driverDB, "Base de datos actualizada", JOptionPane.INFORMATION_MESSAGE);

            }        
    }//GEN-LAST:event_IngresarAñoActionPerformed

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        dispose();
    }//GEN-LAST:event_closeMouseClicked

    private void porDefectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_porDefectoActionPerformed
        int confirm = JOptionPane.showConfirmDialog(rootPane, "¿Estas seguro que deseas usar los parametros por defecto?","Abvertencia!",JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (confirm == JOptionPane.YES_OPTION) {
            nameBD.setText("social");
            gestorBD.setText("mysql");
            rutaBD.setText("com.mysql.jdbc.Driver");
        }
    }//GEN-LAST:event_porDefectoActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfigureDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfigureDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfigureDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfigureDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ConfigureDB dialog = new ConfigureDB(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton IngresarAño;
    private javax.swing.JPanel PanelAñoPlegable;
    private javax.swing.JLabel Texto;
    private javax.swing.JLabel TextoGestor;
    private javax.swing.JLabel TextoNombre;
    private javax.swing.JLabel TextoUrl;
    private javax.swing.JLabel TextoUrl1;
    private javax.swing.JLabel close;
    private javax.swing.JTextField ejemploRuta;
    private javax.swing.JTextField gestorBD;
    private javax.swing.JTextField nameBD;
    private javax.swing.JButton porDefecto;
    private javax.swing.JTextField rutaBD;
    // End of variables declaration//GEN-END:variables
}
